Setup project file
noelfoka/My-portfolio pull request #1
Opened 2023-03-22 11:49 UTC by noelfoka

In this brancg, I did:

- [ ] Added HTML.
- [ ] Added CSS.
- [ ] Edit readme.
- [ ] Added linters.

2023-03-22 16:15 UTC, frank1738 reviewed
Hi @noelfoka , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project with no readme file. Kindly use [this](https://github.com/microverseinc/readme-template) readme file and customize it to contain the project information

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-23 04:05 UTC, shella12 reviewed
Hi @noelfoka , 

#  Status: Invalidated :red_circle: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional README. As mentioned by the previous reviewer please use this [template ](https://github.com/microverseinc/readme-template)link and use the [README template](https://github.com/microverseinc/readme-template) for your README. Also don't forget to customise it by adding details about your project.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-23 09:22 UTC, tufoinnkuo10 requested changes
Hi @noelfoka 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is failing some linter checks. please follow this [guide](https://github.com/microverseinc/linters-config/tree/master/html-css) to set it up.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-23 11:59 UTC, topeogunleye commented on style.css
> +  background-image:
- [ ] [OPTIONAL] It's possible to download and use the background image at once. see a demo below.

https://www.loom.com/share/371616c731d14be1abfdda6805264807

2023-03-23 12:01 UTC, topeogunleye commented on style.css
> +  font-family: Poppins, sans-serif;
- [ ] [OPTIONAL] Poppins is the only font family used in this template, so it's best to declare it in your body selector to keep your css dry, as it'll be inherited from the body selctor to the other selectors.

2023-03-23 12:03 UTC, topeogunleye approved these changes
### **STATUS: APPROVED  ✔️** 
------
Hi @noelfoka,  

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟

![wiserhood-cheers](https://user-images.githubusercontent.com/52934128/180645705-4076a14b-d85b-4173-833e-300c532ceaa6.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good description :heavy_check_mark:

## [Optional] suggestions:
 * [ ]  Please check my inline comments.

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear
Please, remember to tag @topeogunleye in your question so I can receive the notification

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 12:03 UTC, topeogunleye commented on style.css
> +    url("../images/Ellipse\ 15.png");
- [ ] [OPTIONAL] It's possible to download and use the background image at once. see a demo below.

https://www.loom.com/share/371616c731d14be1abfdda6805264807

2023-03-23 12:03 UTC, topeogunleye commented on style.css
> +section p {
- [ ] [OPTIONAL] Poppins is the only font family used in this template, so it's best to declare it in your body selector to keep your css dry, as it'll be inherited from the body selctor to the other selectors.

2023-03-23 12:08 UTC, merged

2023-03-23 13:46 UTC, noelfoka commented on style.css
> +    url("../images/Ellipse\ 15.png");
hank you very much

2023-03-24 04:43 UTC, topeogunleye commented on style.css
> +    url("../images/Ellipse\ 15.png");
> hank you very much

@noelfoka, you're welcome.